### ISSUE TITLE
Socket error processing request 

### ISSUE THREAD

**Issue by naumek** [OWASP/django-DefectDojo#284] opened 2017-05-19 11:57 UTC
Hello,
When I'm trying to push engagement to Jira I'm receiving below error:

dojo_1   | [2017-05-19 06:41:59 +0000] [34] [ERROR] Socket error processing request.
dojo_1   | Traceback (most recent call last):
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
dojo_1   |     self.handle_request(listener, req, client, addr)
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 191, in handle_request
dojo_1   |     six.reraise(*sys.exc_info())
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
dojo_1   |     respiter = self.wsgi(environ, resp.start_response)
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
dojo_1   |     response = self.get_response(request)
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
dojo_1   |     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 256, in handle_uncaught_exception
dojo_1   |     'request': request
dojo_1   |   File "/usr/lib/python2.7/logging/__init__.py", line 1191, in error
dojo_1   |     self._log(ERROR, msg, args, **kwargs)
dojo_1   |   File "/usr/lib/python2.7/logging/__init__.py", line 1284, in _log
dojo_1   |     self.handle(record)
dojo_1   |   File "/usr/lib/python2.7/logging/__init__.py", line 1294, in handle
dojo_1   |     self.callHandlers(record)
dojo_1   |   File "/usr/lib/python2.7/logging/__init__.py", line 1334, in callHandlers
dojo_1   |     hdlr.handle(record)
dojo_1   |   File "/usr/lib/python2.7/logging/__init__.py", line 757, in handle
dojo_1   |     self.emit(record)
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/utils/log.py", line 129, in emit
dojo_1   |     self.send_mail(subject, message, fail_silently=True, html_message=html_message)
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/utils/log.py", line 132, in send_mail
dojo_1   |     mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/core/mail/__init__.py", line 98, in mail_admins
dojo_1   |     mail.send(fail_silently=fail_silently)
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/core/mail/message.py", line 303, in send
dojo_1   |     return self.get_connection(fail_silently).send_messages([self])
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
dojo_1   |     new_conn_created = self.open()
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 58, in open
dojo_1   |     self.connection = connection_class(self.host, self.port, **connection_params)
dojo_1   |   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
dojo_1   |     (code, msg) = self.connect(host, port)
dojo_1   |   File "/usr/lib/python2.7/smtplib.py", line 316, in connect
dojo_1   |     self.sock = self._get_socket(host, port, self.timeout)
dojo_1   |   File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
dojo_1   |     return socket.create_connection((host, port), timeout)
dojo_1   |   File "/usr/lib/python2.7/socket.py", line 557, in create_connection
dojo_1   |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
dojo_1   | gaierror: [Errno -2] Name or service not known

For me it looks like problems with sending mails.

I'm using a docker version (Linux kernel 4.9.13-moby).

**Comment by devGregA** [comment] 2017-05-20 03:09
Hi @naumek thank you for your report! I haven't seen this issue before, give me a couple of days to investigate.

**Comment by naumek** [comment] 2017-05-22 15:48
Hello,
I think it might be connected to report engine. Looks like I'm unable to create a pdf report. Here is a output:

dojo_1   | [2017-05-22 10:45:54,858: INFO/MainProcess] Received task: dojo.tasks.async_custom_pdf_report[6a970bac-83d6-4fe5-8740-117c5362e9a8]
dojo_1   | [2017-05-22 10:45:55,006: ERROR/MainProcess] Task dojo.tasks.async_custom_pdf_report[6a970bac-83d6-4fe5-8740-117c5362e9a8] raised unexpected: TemplateSyntaxError(u"Could not parse the remainder: '{ finding.id' from '{ finding.id'",)
dojo_1   | Traceback (most recent call last):
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
dojo_1   |     R = retval = fun(*args, **kwargs)
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
dojo_1   |     return self.run(*args, **kwargs)
dojo_1   |   File "/django-DefectDojo/dojo/tasks.py", line 174, in async_custom_pdf_report
dojo_1   |     raise e
dojo_1   | TemplateSyntaxError: Could not parse the remainder: '{ finding.id' from '{ finding.id'
nginx_1  | 2017/05/22 15:45:55 [error] 7#7: *27 open() "/django-DefectDojo/static/startbootstrap-sb-admin-2/dist/css/timeline.css" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /static/startbootstrap-sb-admin-2/dist/css/timeline.css HTTP/1.1", host: "localhost", referrer: "https://localhost/reports"
dojo_1   | [2017-05-22 10:45:55,008: ERROR/MainProcess] Pool callback raised exception: ValueError('too many values to unpack',)
dojo_1   | Traceback (most recent call last):
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/billiard/pool.py", line 1700, in safe_apply_callback
dojo_1   |     fun(*args, **kwargs)
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/worker/job.py", line 384, in on_success
dojo_1   |     return self.on_failure(ret_value)
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/worker/job.py", line 443, in on_failure
dojo_1   |     self._log_error(exc_info, send_failed_event=send_failed_event)
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/worker/job.py", line 514, in _log_error
dojo_1   |     task.send_error_email(context, einfo.exception)
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/app/task.py", line 900, in send_error_email
dojo_1   |     self.ErrorMail(self, **kwargs).send(context, exc)
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/utils/mail.py", line 190, in send
dojo_1   |     fail_silently=fail_silently)
dojo_1   |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/app/base.py", line 416, in mail_admins
dojo_1   |     to = [admin_email for _, admin_email in self.conf.ADMINS]
dojo_1   | ValueError: too many values to unpack


Have u seen this issue before?


nmk

**Comment by devGregA** [comment] 2017-05-23 21:28
@naumek for the second one, you might have an old version of wkhtml. If you're running ubuntu the `reports.sh` script is very helpful please see https://github.com/OWASP/django-DefectDojo/issues/285

**Comment by devGregA** [comment] 2017-05-23 21:29
@naumek ah sorry. just saw you're using docker. @aaronweaver is the docker master, but I know he is very busy right now

**Comment by naumek** [comment] 2017-05-26 08:55
@devGregA  wkhtml - that was first thing on my mind - I'm using latest version.

**Comment by devGregA** [comment] 2017-06-07 14:42
@naumek did you ever get this resolved? It sounded like from your email that you were pushing issues?

**Comment by naumek** [comment] 2017-06-07 14:46
Still fighting with it....

**Comment by devGregA** [comment] 2017-07-04 18:54
@naumek, I'm sorry but I have been unable to reproduce this issue. Here are the other things I'm thinking that might help:
1. Running Dojo on Ubuntu 16.04
2. pulling the latest code
3. Use reports.sh to pull the latest wkhtmltopdf
4. ensure the wkhtmltopdf path in settings points to the output of 'which wkhtmltopdf'

**Comment by devGregA** [comment] 2017-07-04 19:00
It also looks like you're using gunicorn? I would recommend uwsgi

**Comment by devGregA** [comment] 2017-07-11 22:49
closing due to no repsonse

**Closed by devGregA** 2017-07-11 22:49 UTC
Labels: unable to reproduce
